pycon_project/biblion/urls.py
from django.conf.urls.defaults import *

from django.views.generic.simple import direct_to_template


urlpatterns = patterns("",
    url(r'^$', "biblion.views.blog_index", name="blog"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', "biblion.views.blog_post_detail", name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', "biblion.views.blog_post_detail", name="blog_post_pk"),
    url(r'^(?P<section>[-\w]+)/$', "biblion.views.blog_section_list", name="blog_section"),
)

pycon_project/pycon_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
admin.autodiscover()

# from pinax.apps.account.openid_consumer import PinaxConsumer

urlpatterns = patterns("",
    (r'^i18n/', include('django.conf.urls.i18n')),
)

handler500 = "pinax.views.server_error"

urlpatterns += i18n_patterns("",
        url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
        url(r"^program/$", direct_to_template, {"template": "pycon/program.html"}, name="program"),
        url(r"^tutorial/$", direct_to_template, {"template": "pycon/tutorial.html"}, name="tutorial"),
        url(r"^account/signup/$", "pinax.apps.account.views.signup", name="acct_signup"),
        url(r"^account/", include("pinax.apps.account.urls")),
        # url(r"^openid/", include(PinaxConsumer().urls)),
        # url(r"^oauth_access/finish_signup/(?P<service>\w+)/$", "oauth_callbacks.finish_signup", name="oauth_access_finish_signup"),
        # url(r"^oauth_access/", include("oauth_access.urls")),
        url(r"^blog/", include("biblion.urls")),
        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposal/", include("symposion.proposals.urls")),
        url(r"^review/", include("symposion.review.urls")),
        url(r"^waitinglist/", include("pinax.apps.waitinglist.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^mailout/", include("mailout.urls")),
        url(r"^sponsors/", include("symposion.sponsors_pro.urls")),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^creole_preview/$", "pycon_project.views.creole_preview", name="creole_preview"),
        url(r"^feed/(?P<section>\w+)/$", "biblion.views.blog_feed", name="blog_feed"),
        url(r"^markitup/", include("markitup.urls")),
        # url(r"^export_data/speakers\.txt$", "schedule.views.schedule_export_speaker_data"),
        # url(r"^export_data/sponsors\.txt$", "sponsors.views.sponsor_export_data"),
        # url(r"^export_data/panels\.txt$", "schedule.views.schedule_export_panels"),
        url(r"^about/$", direct_to_template, {"template": "pycon/about.html"}, name="about"),
        url(r"^registration/$", direct_to_template, {"template": "pycon/registration.html"}, name="registration"),
        url(r"^venue/$", direct_to_template, {"template": "venue/detail.html"}, name="venue_detail"),
        url(r"^venue/traveling/", direct_to_template, {"template": "venue/traveling.html"}, name="traveling"),
        url(r"^venue/directions/", direct_to_template, {"template": "venue/directions.html"}, name="directions"),
        url(r"^venue/getting-around/", direct_to_template, {"template": "venue/getting_around.html"}, name="getting_around"),
        url(r"^venue/weather/", direct_to_template, {"template": "venue/weather.html"}, name="weather"),
        url(r"^venue/explore/", direct_to_template, {"template": "venue/explore.html"}, name="explore"),
        url(r"^venue/restaurants/", direct_to_template, {"template": "venue/restaurants.html"}, name="restaurants"),
        url(r"^venue/bars/", direct_to_template, {"template": "venue/bars.html"}, name="bars"),
        url(r"^venue/shopping/", direct_to_template, {"template": "venue/shopping.html"}, name="shopping"),
        url(r"^venue/share-room/", direct_to_template, {"template": "venue/share_room.html"}, name="share_room"),


        url(r"^boxes/", include("boxes.urls")),
        # url(r"^", include("wakawaka.urls")),

    )

# urlpatterns += i18n_patterns("",
#     url(r"^$", include(content_patterns)),
#     url(r"^%s/" % settings.PYCON_YEAR, include(content_patterns)),
# )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"^favicon.ico$", redirect_to, {
            "url": settings.STATIC_URL + "img/favicon.ico",
        }),
        url(r"^%s/site_media/media/(?P<path>.*)$" % settings.PYCON_YEAR, "django.views.static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
    )

pycon_project/symposion/speakers/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns("symposion.speakers.views",
    url(r"^$", "speaker_dashboard", name="speaker_dashboard"),
    url(r"^create/$", "speaker_create", name="speaker_create"),
    url(r"^create/(\w+)/$", "speaker_create_token", name="speaker_create_token"),
    url(r"^edit/(?:(?P<pk>\d+)/)?$", "speaker_edit", name="speaker_edit"),
    url(r"^profile/(?P<pk>\d+)/$", "speaker_profile", name="speaker_profile"),
)

pycon_project/symposion/speakers/models.py
import datetime

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User

from markitup.fields import MarkupField


class Speaker(models.Model):

    # SESSION_TYPE_CHOICES = [
    #     (1, _("Regular Talk (30 minutes)")),
    #     (2, _("Lightning Talk (5 minutes)"))
    # ]

    user = models.OneToOneField(User, null=True, related_name="speaker_profile")
    name = models.CharField(_("Name"), max_length=100)
    nickname = models.CharField(_("Nickname"), max_length=100, blank=True, default="")
    biography = MarkupField(_("Biography"), help_text=_("A little bit about you. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>."))
    photo = models.ImageField(_("Photo"), upload_to="speaker_photos", blank=True, help_text=_('Please upload JPG with 950x1190 dimension above'))
    twitter_username = models.CharField(
        _("Twitter username"),
        max_length = 15,
        blank = True,
        help_text = _("Your Twitter account, with or without the @")
    )
    annotation = models.TextField()  # staff only
    invite_email = models.CharField(max_length=200, unique=True, null=True, db_index=True)
    invite_token = models.CharField(max_length=40, db_index=True)
    release_permission = models.BooleanField(_("Agree to Release"), help_text=_('I agree PyCon TW can release my slides and video recording.'))
    created = models.DateTimeField(
        default = datetime.datetime.now,
        editable = False
    )
    # sessions_preference = models.IntegerField(
    #     _("Talk Types"),
    #     choices=SESSION_TYPE_CHOICES,
    #     null=True,
    #     blank=True,
    #     help_text=_("If you're not sure which type to choose, select 'Regular Talk' here, and discuss with Program Team for a better arrangement.")
    # )

    def __unicode__(self):
        if self.user:
            return self.name
        else:
            return "?"

    def get_absolute_url(self):
        return reverse("speaker_edit")

    @property
    def email(self):
        if self.user is not None:
            return self.user.email
        else:
            return self.invite_email

pycon_project/symposion/speakers/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from django.contrib import messages

from pinax.apps.account.forms import SignupForm as PinaxSignupForm

from emailconfirmation.models import EmailAddress

from markitup.widgets import MarkItUpWidget

from symposion.speakers.models import Speaker


class SpeakerForm(forms.ModelForm):

    # sessions_preference = forms.ChoiceField(
    #     label=_('Talk Types'),
    #     widget=forms.RadioSelect(),
    #     choices=Speaker.SESSION_TYPE_CHOICES,
    #     required=False,
    #     help_text=_("If you're not sure which type to choose, select 'Regular Talk' here, and discuss with Program Team for a better arrangement.")
    # )

    class Meta:
        model = Speaker
        fields = [
            "name",
            "nickname",
            "biography",
            "photo",
            "twitter_username",
            # "sessions_preference",
            "release_permission",
        ]
        widgets = {
            "biography": MarkItUpWidget(),
        }

    def clean_twitter_username(self):
        value = self.cleaned_data["twitter_username"]
        if value.startswith("@"):
            value = value[1:]
        return value

    # def clean_sessions_preference(self):
    #     value = self.cleaned_data["sessions_preference"]
    #     if not value:
    #         return None
    #     return int(value)


class SignupForm(PinaxSignupForm):

    def save(self, speaker, request=None):
        # don't assume a username is available. it is a common removal if
        # site developer wants to use email authentication.
        username = self.cleaned_data.get("username")
        email = self.cleaned_data["email"]
        new_user = self.create_user(username)
        if speaker.invite_email == new_user.email:
            # already verified so can just create
            EmailAddress(user=new_user, email=email, verified=True, primary=True).save()
        else:
            if request:
                messages.info(request, u"Confirmation email sent to %(email)s" % {"email": email})
            EmailAddress.objects.add_email(new_user, email)
            new_user.is_active = False
            new_user.save()
        self.after_signup(new_user)
        return new_user

pycon_project/symposion/speakers/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import Http404
from django.utils.translation import ugettext as _
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from pinax.apps.account.forms import LoginForm

from symposion.proposals.models import Proposal
from symposion.speakers.forms import SpeakerForm, SignupForm
from symposion.speakers.models import Speaker


def speaker_dashboard(request):
    ctx = {}
    if request.user.is_authenticated():
        if Speaker.objects.filter(user=request.user).exists():
            proposals = Proposal.objects.filter(
                Q(speaker=request.user.speaker_profile) |
                Q(additional_speakers=request.user.speaker_profile)
            ).distinct()
            if proposals.count():
                ctx["proposal_text"] = _("submit another talk proposal")
            else:
                ctx["proposal_text"] = _("submit a talk proposal")
            ctx["proposals"] = proposals
            template_name = "dashboard_auth_speaker.html"
        else:
            template_name = "dashboard_auth_nospeaker.html"
    else:
        template_name = "dashboard_noauth.html"
    ctx["accepting_proposals"] = settings.ACCEPTING_PROPOSALS
    ctx["accept_speakers"] = set(Speaker.objects.filter(proposals__result__accepted=True).prefetch_related("proposals"))
    ctx = RequestContext(request, ctx)
    return render_to_response("speakers/%s" % template_name, ctx)


@login_required
def speaker_create(request):
    try:
        return redirect(request.user.speaker_profile)
    except ObjectDoesNotExist:
        pass
    if request.method == "POST":
        try:
            speaker = Speaker.objects.get(invite_email=request.user.email)
            found = True
        except Speaker.DoesNotExist:
            speaker = None
            found = False
        form = SpeakerForm(request.POST, request.FILES, instance=speaker)
        if form.is_valid():
            speaker = form.save(commit=False)
            speaker.user = request.user
            if not found:
                speaker.invite_email = None
            speaker.save()
            messages.success(request, "Speaker profile created.")
            return redirect("speaker_dashboard")
    else:
        form = SpeakerForm()
    ctx = {
        "form": form,
    }
    ctx = RequestContext(request, ctx)
    return render_to_response("speakers/speaker_create.html", ctx)


def speaker_create_token(request, token):
    speaker = get_object_or_404(Speaker, invite_token=token)
    if request.user.is_authenticated():
        # check for speaker profile
        try:
            existing_speaker = request.user.speaker_profile
        except ObjectDoesNotExist:
            pass
        else:
            additional_speakers = Proposal.additional_speakers.through
            additional_speakers._default_manager.filter(
                speaker = speaker
            ).update(
                speaker = existing_speaker
            )
            messages.info(request, "You have been associated with all pending "
                "talk proposals")
            return redirect("speaker_dashboard")
    if request.method == "POST":
        if "login" in request.POST:
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                login_form.login(request)
                return redirect("speaker_create_token", token)
            else:
                signup_form = SignupForm(initial={"email": speaker.invite_email}, prefix="signup")
                speaker_form = None
        elif "signup" in request.POST:
            login_form = None
            forms = []
            if not request.user.is_authenticated():
                login_form = None
                signup_form = SignupForm(request.POST, prefix="signup")
                forms.append(signup_form)
            speaker_form = SpeakerForm(request.POST, request.FILES,
                prefix = "speaker",
                instance = speaker
            )
            forms.append(speaker_form)
            if all([f.is_valid() for f in forms]):
                if not request.user.is_authenticated():
                    user = signup_form.save(speaker, request=request)
                else:
                    user = request.user
                speaker = speaker_form.save(commit=False)
                speaker.user = user
                speaker.save()
                if not request.user.is_authenticated():
                    if user.email != speaker.invite_email:
                        ctx = {
                            "email": user.email,
                            "success_url": "/",
                        }
                        ctx = RequestContext(request, ctx)
                        return render_to_response("account/verification_sent.html", ctx)
                    else:
                        signup_form.login(request, user)
                return redirect("speaker_dashboard")
        else:
            raise Exception("wtf?")
    else:
        if not request.user.is_authenticated():
            login_form = LoginForm()
            signup_form = SignupForm(initial={"email": speaker.invite_email}, prefix="signup")
        else:
            login_form, signup_form = None, None
        speaker_form = SpeakerForm(prefix="speaker")
    ctx = {
        "login_form": login_form,
        "signup_form": signup_form,
        "speaker_form": speaker_form,
    }
    ctx = RequestContext(request, ctx)
    return render_to_response("speakers/speaker_create_token.html", ctx)


@login_required
def speaker_edit(request, pk=None):
    if pk is None:
        try:
            speaker = request.user.speaker_profile
        except Speaker.DoesNotExist:
            return redirect("speaker_create")
    else:
        if request.user.groups.filter(name="organizer").exists():
            speaker = get_object_or_404(Speaker, pk=pk)
        else:
            raise Http404()
    if request.method == "POST":
        form = SpeakerForm(request.POST, request.FILES, instance=speaker)
        if form.is_valid():
            form.save()

            speaker_admin_url = 'http://%s/2013/admin/speakers/speaker/%d/' % (request.get_host(), speaker.pk)
            content = "%s updated his profile.\n\n %s" % (speaker.name, speaker_admin_url)
            send_mail('[PyConTW] Speaker profile updated', content, settings.DEFAULT_FROM_EMAIL, [settings.CONTACT_EMAIL])

            messages.success(request, "Speaker profile updated.")
            return redirect("speaker_dashboard")
    else:
        form = SpeakerForm(instance=speaker)
    ctx = {
        "form": form,
    }
    ctx = RequestContext(request, ctx)
    return render_to_response("speakers/speaker_edit.html", ctx)


def speaker_profile(request, pk, template_name="speakers/speaker_profile.html", extra_context=None):

    if extra_context is None:
        extra_context = {}

    speaker = get_object_or_404(Speaker, pk=pk)

    # schedule may not be installed so we need to check for sessions
    if hasattr(speaker, "sessions"):
        sessions = speaker.sessions.exclude(slot=None).order_by("slot__start")
    else:
        sessions = []

    if not sessions:
        raise Http404()

    return render_to_response(template_name, dict({
        "speaker": speaker,
        "sessions": sessions,
        "timezone": settings.SCHEDULE_TIMEZONE,
    }, **extra_context), context_instance=RequestContext(request))

pycon_project/templates/speakers/base.html
{% extends "site_base.html" %}
{% load i18n %}

{% block body_class %}full speaker{% endblock %}

{% block head_title_base %}{% trans "Speakers" %} / {{ block.super }}{% endblock %}

{% block body %}
    <h1 class="section-title">{% block subpage_title %}{% blocktrans %}Speaker <span>Information</span>{% endblocktrans %}{% endblock %}</h1>
    {% block content %}{% endblock %}
{% endblock body %}


{% block right %}{% endblock %}

pycon_project/templates/speakers/dashboard_auth_nospeaker.html
{% extends "speakers/base.html" %}
{% load boxes_tags i18n %}

{% block content %}

    <p>{% box "talk-proposals" %}</p>

    {% include "speakers/dashboard_speaker_lists.html" %}

    {% if accepting_proposals %}

        <h3>{% trans "To submit a talk" %}:</h3>

        <ol class="steps">
            <li class="done first">{% trans "sign up and log in" %}</li>
            <li class="next second"><a href="{% url speaker_create %}">{% trans "create a speaker profile" %}</a></li>
            <li class="third">{% trans "submit one or more proposals" %}</li>
        </ol>

        <p>{% blocktrans %}You will be able to come back and revise your submission until the deadline. Remember that speakers must register and pay to attend the conference.{% endblocktrans %}</p>
    {% else %}
        <p>{% trans "Talk submissions are now closed." %}</p>
    {% endif %}
{% endblock %}

pycon_project/templates/speakers/dashboard_auth_speaker.html
{% extends "speakers/base.html" %}
{% load boxes_tags i18n %}

{% block content %}
    <p>{% box "talk-proposals" %}</p>

    {% include "speakers/dashboard_speaker_lists.html" %}


    <h2>{% trans "Edit Speaker Profile" %}</h2>
    <p><a class="btn" href="{% url speaker_edit %}">{% trans "Edit your speaker profile" %}</a></p>

    {% if accepting_proposals %}
        <h3>{% trans "To submit a talk" %}</h3>

        <ol class="steps">
            <li class="done first">{% trans "sign up and log in" %}</li>
            <li class="done second">{% trans "create a speaker profile" %}</li>
            <li class="next third"><a href="{% url proposal_submit %}">{{ proposal_text }}</a></li>
        </ol>

        <p>{% blocktrans %}You will be able to come back and revise your submission until the deadline. Remember that speakers must register and pay to attend the conference.{% endblocktrans %}</p>
    {% else %}
        <p>{% trans "Talk submissions are now closed." %}</p>

    {% endif %}

    <h3>{% trans "Proposals" %}</h3>

    {% if proposals %}
        <table class="table proposals">
            <thead>
            <tr>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Session type" %}</th>
                <th>{% trans "Audience level" %}</th>
                <th>{% trans "Status" %}</th>
                <th>{% trans "Messages" %}</th>
                <th>{% trans "Actions" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for proposal in proposals %}
            <tr>
                <td><a href="{% url proposal_detail proposal.pk %}">{{ proposal.title }}</a></td>
                <td>{{ proposal.get_kind_display }}</td>
                <td>{{ proposal.get_audience_level_display }}</td>
                <td>
                    {% if proposal.cancelled %}
                        {% trans "Cancelled" %}
                    {% else %}
                        {% if request.user == proposal.speaker.user %}
                            {% if proposal.result.accepted %}
                                {% trans "Accepted" %}
                            {% else %}
                                {% trans "Submitted" %}
                            {% endif %}
                        {% else %}
                            {% trans "Associated" %}
                        {% endif %}
                    {% endif %}
                </td>
                <td>{{ proposal.messages.all.count }}</td>
                {# <td>{% if not proposal.cancelled %}{% if request.user == proposal.speaker.user %}<a href="{% url proposal_edit proposal.pk %}">Edit</a>{% endif %}{% if request.user == proposal.speaker.user %} | <a href="{% url proposal_cancel proposal.pk %}">Cancel</a>{% else %}<a href="{% url proposal_leave proposal.pk %}">Leave</a>{% endif %}{% endif %}</td> #}
                <td>
                    {% if not proposal.cancelled %}
                        {% if request.user == proposal.speaker.user and proposal.can_edit %}
                            <a href="{% url proposal_edit proposal.pk %}">{% trans "Edit" %}</a> |
                            <a href="{% url proposal_speaker_manage proposal.id %}">{% trans "Add/Remove Speakers" %}</a>
                            {% if proposal.result.accepted %}
                            |
                                {% if proposal.files.exists %}
                                    {% trans "Slides/Paper uploaded" %}

                                    ( <a href="{% url proposal_file proposal.id %}">{% trans "Update" %}</a> )
                                {% else %}
                                    <a href="{% url proposal_file proposal.id %}">{% trans "Upload Slides/Paper" %}</a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        {% url proposal_submit as proposal_submit_url %}
        <p>{% trans "No proposals" %}. {% blocktrans %}You can <a href="{{ proposal_submit_url }}">submit one</a> now!{% endblocktrans %}</p>
    {% endif %}

{% endblock %}

pycon_project/templates/speakers/dashboard_noauth.html
{% extends "speakers/base.html" %}
{% load boxes_tags i18n %}

{% block content %}
    <p>{% box "talk-proposals" %}</p>

    {% include "speakers/dashboard_speaker_lists.html" %}

    {% if accepting_proposals %}
        <h3>{% trans "To submit a talk" %}:</h3>

        <ol class="steps">
            <li class="next first"><a href="{% url acct_signup %}?next={{ request.path }}">{% trans "sign up" %}</a> {% trans "and" %} <a href="{% url acct_login %}?next={{ request.path }}">{% trans "log in" %}</a></li>
            <li class="second">{% trans "create a speaker profile" %}</li>
            <li class="third">{% trans "submit one or more proposals" %}</li>
        </ol>
    {% endif %}
{% endblock %}

pycon_project/templates/speakers/dashboard_speaker_lists.html
{% load i18n thumbnail %}

<div class="speakers">
    {% for speaker in accept_speakers %}

        <a id="speaker_id_{{ speaker.id }}"></a>
        {% if not forloop.first %}
        <div class="row-fluid">
            <div class="span12">
                <hr/>
            </div>
        </div>
        <div class="row-fluid hidden-phone"> <!-- extra space below <hr/> for non-phone layout -->
            <div class="span12">&nbsp;</div>
        </div>
        {% endif %}

        <div class="row-fluid">
            <div class="span3 namephoto">
                <strong>{{ speaker.name }}</strong>

                {% if speaker.nickname %}
                    <br/>
                    ({{ speaker.nickname }})
                {% endif %}
                {% if speaker.photo %}
                    <br/>
                    {% thumbnail speaker.photo "200" format="PNG" as im %}
                        <img src="{{ im.url }}" alt="{{ speaker.name }}">
                    {% endthumbnail %}

                    <!-- extra space below photo for phone layout -->
                    <div class="visible-phone">&nbsp;</div>
                {% endif %}
            </div>
            <div class="span9 bio">
                {{ speaker.biography|safe }}

                <p><strong>{% trans "Talk(s)" %}</strong></p>
                <ul>
                {% for proposal in speaker.proposals.all %}
                    {% if proposal.result.accepted %}
                    <li>{{ proposal.title }}</li>
                    {% endif %}
                {% endfor %}
                </ul>
            </div>
        </div>

    {% endfor %}
</div>

pycon_project/templates/speakers/speaker_create.html
{% extends "speakers/base.html" %}

{% load markitup_tags %}
{% load bootstrap %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/speakers.css" />
{% endblock %}

    
{% block content %}
    {% markitup_media %}
    <form method="post" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap }}
            <div class="form-actions">
                <input class="btn btn-primary" type="submit" value="submit" />
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block extra_body %}
    <script type="text/javascript">
    $(function() {
        $("#id_name").focus();
    });
    </script>
    <script src="{{ STATIC_URL }}js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $.facebox.settings.loadingImage = '{{ STATIC_URL }}img/facebox/loading.gif';
            $.facebox.settings.closeImage = '{{ STATIC_URL }}img/facebox/closelabel.gif';
            $('#preview').click(function() {
                var raw = $("#id_biography").val();
                $.facebox.loading();
                $.post(
                    '{% url creole_preview %}',
                    {raw: raw},
                    function(data) {
                        $.facebox(data)
                    }
                );
                return false;
            });
        });
    </script>
{% endblock %}

pycon_project/templates/speakers/speaker_create_token.html
{% extends "speakers/base.html" %}

{% load uni_form_tags %}

{% block content %}
    
    {% if not request.user.is_authenticated %}
        {% if login_form %}
            <h2>Log In To Your Existing Account</h2>
            
            <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
                {% csrf_token %}
                <fieldset class="inlineLabels">
                    {{ login_form|as_uni_form }}
                    <div class="form_block">
                        <input type="submit" name="login" value="log in" />
                    </div>
                </fieldset>
            </form>
            
            <p><b>- or -</b></p>
        {% endif %}
        
        <h2>Create An Account and Speaker Profile</h2>
        
        <p>You've been attached as an additional speaker to a talk proposal for PyCon 2011. Create yourself an account and speaker profile by filling out the form below. You will be able to see the proposal(s) you've been invited to once signed up.</p>
        
        <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
            {% csrf_token %}
            <fieldset class="inlineLabels">
                {{ signup_form|as_uni_form }}
            </fieldset>
            <fieldset class="inlineLabels">
                {{ speaker_form|as_uni_form }}
                <div class="form_block">
                    <input type="submit" name="signup" value="submit" />
                </div>
            </fieldset>
        </form>
    {% else %}
        
        <h2>Create Your Speaker Profile</h2>
        
        <p>You were attached as an additional speaker to a talk proposal for PyCon 2011, but have not created a speaker profile. Create your speaker profile below.</p>
        
        <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
            {% csrf_token %}
            <fieldset class="inlineLabels">
                {{ speaker_form|as_uni_form }}
                <div class="form_block">
                    <input type="submit" name="signup" value="create" />
                </div>
            </fieldset>
        </form>
    {% endif %}
{% endblock %}

pycon_project/templates/speakers/speaker_edit.html
{% extends "speakers/base.html" %}
{% load i18n %}

{% load markitup_tags bootstrap %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/speakers.css" />
{% endblock %}

{% block body %}
    <h1>{% trans "Edit Speaker Profile" %}</h1>
    
    {% markitup_media %}
    <form method="post" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <fieldset>

            {{ form|bootstrap }}

            <div class="form-actions">
                <input class="btn btn-primary" type="submit" value="submit" />
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $.facebox.settings.loadingImage = '{{ STATIC_URL }}img/facebox/loading.gif';
            $.facebox.settings.closeImage = '{{ STATIC_URL }}img/facebox/closelabel.gif';
            $('#preview').click(function() {
                var raw = $("#id_biography").val();
                $.facebox.loading();
                $.post(
                    '{% url creole_preview %}',
                    {raw: raw},
                    function(data) {
                        $.facebox(data)
                    }
                );
                return false;
            });
        });
    </script>
{% endblock %}