pycon_project/biblion/urls.py
from django.conf.urls.defaults import *

from django.views.generic.simple import direct_to_template


urlpatterns = patterns("",
    url(r'^$', "biblion.views.blog_index", name="blog"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', "biblion.views.blog_post_detail", name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', "biblion.views.blog_post_detail", name="blog_post_pk"),
    url(r'^(?P<section>[-\w]+)/$', "biblion.views.blog_section_list", name="blog_section"),
)

pycon_project/pycon_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
admin.autodiscover()

# from pinax.apps.account.openid_consumer import PinaxConsumer

urlpatterns = patterns("",
    (r'^i18n/', include('django.conf.urls.i18n')),
)

handler500 = "pinax.views.server_error"

urlpatterns += i18n_patterns("",
        url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
        url(r"^program/$", direct_to_template, {"template": "pycon/program.html"}, name="program"),
        url(r"^tutorial/$", direct_to_template, {"template": "pycon/tutorial.html"}, name="tutorial"),
        url(r"^account/signup/$", "pinax.apps.account.views.signup", name="acct_signup"),
        url(r"^account/", include("pinax.apps.account.urls")),
        # url(r"^openid/", include(PinaxConsumer().urls)),
        # url(r"^oauth_access/finish_signup/(?P<service>\w+)/$", "oauth_callbacks.finish_signup", name="oauth_access_finish_signup"),
        # url(r"^oauth_access/", include("oauth_access.urls")),
        url(r"^blog/", include("biblion.urls")),
        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposal/", include("symposion.proposals.urls")),
        url(r"^review/", include("symposion.review.urls")),
        url(r"^waitinglist/", include("pinax.apps.waitinglist.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^mailout/", include("mailout.urls")),
        url(r"^sponsors/", include("symposion.sponsors_pro.urls")),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^creole_preview/$", "pycon_project.views.creole_preview", name="creole_preview"),
        url(r"^feed/(?P<section>\w+)/$", "biblion.views.blog_feed", name="blog_feed"),
        url(r"^markitup/", include("markitup.urls")),
        # url(r"^export_data/speakers\.txt$", "schedule.views.schedule_export_speaker_data"),
        # url(r"^export_data/sponsors\.txt$", "sponsors.views.sponsor_export_data"),
        # url(r"^export_data/panels\.txt$", "schedule.views.schedule_export_panels"),
        url(r"^about/$", direct_to_template, {"template": "pycon/about.html"}, name="about"),
        url(r"^registration/$", direct_to_template, {"template": "pycon/registration.html"}, name="registration"),
        url(r"^venue/$", direct_to_template, {"template": "venue/detail.html"}, name="venue_detail"),
        url(r"^venue/traveling/", direct_to_template, {"template": "venue/traveling.html"}, name="traveling"),
        url(r"^venue/directions/", direct_to_template, {"template": "venue/directions.html"}, name="directions"),
        url(r"^venue/getting-around/", direct_to_template, {"template": "venue/getting_around.html"}, name="getting_around"),
        url(r"^venue/weather/", direct_to_template, {"template": "venue/weather.html"}, name="weather"),
        url(r"^venue/explore/", direct_to_template, {"template": "venue/explore.html"}, name="explore"),
        url(r"^venue/restaurants/", direct_to_template, {"template": "venue/restaurants.html"}, name="restaurants"),
        url(r"^venue/bars/", direct_to_template, {"template": "venue/bars.html"}, name="bars"),
        url(r"^venue/shopping/", direct_to_template, {"template": "venue/shopping.html"}, name="shopping"),
        url(r"^venue/share-room/", direct_to_template, {"template": "venue/share_room.html"}, name="share_room"),


        url(r"^boxes/", include("boxes.urls")),
        # url(r"^", include("wakawaka.urls")),

    )

# urlpatterns += i18n_patterns("",
#     url(r"^$", include(content_patterns)),
#     url(r"^%s/" % settings.PYCON_YEAR, include(content_patterns)),
# )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"^favicon.ico$", redirect_to, {
            "url": settings.STATIC_URL + "img/favicon.ico",
        }),
        url(r"^%s/site_media/media/(?P<path>.*)$" % settings.PYCON_YEAR, "django.views.static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
    )

pycon_project/symposion/review/urls.py
from django.conf.urls.defaults import patterns, url, include


urlpatterns = patterns("symposion.review.views",
    url(r"^list/$", "review_list", name="review_list"),
    url(r"^list/(?P<username>[\w\-]+)/$", "review_list", name="review_list_user"),
    url(r"^tutorial/list/$", "review_tutorial_list", name="review_tutorial_list"),
    url(r"^tutorial/list/(?P<username>[\w\-]+)/$", "review_tutorial_list", name="review_tutorial_list_user"),
    url(r"^admin/$", "review_admin", name="review_admin"),
    url(r"^admin/accept/$", "review_bulk_accept", name="review_bulk_accept"),
    url(r"^stats/$", "review_stats", name="review_stats"),
    url(r"^stats/(?P<key>[\w]+)/$", "review_stats", name="review_stats_key"),
    url(r"^(?P<pk>\d+)/$", "review_detail", name="review_detail"),
    url(r"^(?P<pk>\d+)/delete/$", "review_delete", name="review_delete"),
    url(r"^assignments/$", "review_assignments", name="review_assignments"),
    url(r"^assignment/(?P<pk>\d+)/opt-out/$", "review_assignment_opt_out", name="review_assignment_opt_out"),
)

pycon_project/symposion/review/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
from decimal import Decimal

from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save

from django.contrib.auth.models import User

from markitup.fields import MarkupField

from symposion.proposals.models import Proposal
from symposion.schedule.models import Presentation


class ProposalScoreExpression(object):
    
    def as_sql(self, qn, connection=None):
        sql = "((3 * plus_one + plus_zero) - (minus_zero + 3 * minus_one))"
        return sql, []
    
    def prepare_database_save(self, unused):
        return self


class Votes(object):
    PLUS_ONE = "+1"
    PLUS_ZERO = "+0"
    MINUS_ZERO = u"−0"
    MINUS_ONE = u"−1"
    
    CHOICES = [
        (PLUS_ONE, u"+1 — Good proposal and I will argue for it to be accepted."),
        (PLUS_ZERO, u"+0 — OK proposal, but I will not argue for it to be accepted."),
        (MINUS_ZERO, u"−0 — Weak proposal, but I will not argue strongly against acceptance."),
        (MINUS_ONE, u"−1 — Serious issues and I will argue to reject this proposal."),
    ]
VOTES = Votes()


class ReviewAssignment(models.Model):
    AUTO_ASSIGNED_INITIAL = 0
    OPT_IN = 1
    AUTO_ASSIGNED_LATER = 2
    
    ORIGIN_CHOICES = [
        (AUTO_ASSIGNED_INITIAL, "auto-assigned, initial"),
        (OPT_IN, "opted-in"),
        (AUTO_ASSIGNED_LATER, "auto-assigned, later"),
    ]
    
    proposal = models.ForeignKey("proposals.Proposal")
    user = models.ForeignKey(User)
    
    origin = models.IntegerField(choices=ORIGIN_CHOICES)
    
    assigned_at = models.DateTimeField(default=datetime.now)
    opted_out = models.BooleanField()
    
    @classmethod
    def create_assignments(cls, proposal, origin=AUTO_ASSIGNED_INITIAL):
        speakers = [proposal.speaker] + list(proposal.additional_speakers.all())
        reviewers = User.objects.exclude(
            pk__in=[
                speaker.user_id
                for speaker in speakers
                if speaker.user_id is not None
            ]
        ).filter(
            groups__name="reviewers",
        ).filter(
            Q(reviewassignment__opted_out=False) | Q(reviewassignment=None)
        ).annotate(
            num_assignments=models.Count("reviewassignment")
        ).order_by(
            "num_assignments",
        )
        for reviewer in reviewers[:3]:
            cls._default_manager.create(
                proposal=proposal,
                user=reviewer,
                origin=origin,
            )


class ProposalMessage(models.Model):
    proposal = models.ForeignKey("proposals.Proposal", related_name="messages")
    user = models.ForeignKey(User)
    
    message = MarkupField()
    submitted_at = models.DateTimeField(default=datetime.now, editable=False)

    class Meta:
        ordering = ["submitted_at"]


class Review(models.Model):
    VOTES = VOTES
    
    proposal = models.ForeignKey("proposals.Proposal", related_name="reviews")
    user = models.ForeignKey(User)
    
    # No way to encode "-0" vs. "+0" into an IntegerField, and I don't feel
    # like some complicated encoding system.
    vote = models.CharField(max_length=2, blank=True, choices=VOTES.CHOICES)
    comment = MarkupField()
    submitted_at = models.DateTimeField(default=datetime.now, editable=False)
    
    def save(self, **kwargs):
        if self.vote:
            vote, created = LatestVote.objects.get_or_create(
                proposal = self.proposal,
                user = self.user,
                defaults = dict(
                    vote = self.vote,
                    submitted_at = self.submitted_at,
                )
            )
            if not created:
                LatestVote.objects.filter(pk=vote.pk).update(vote=self.vote)
                self.proposal.result.update_vote(self.vote, previous=vote.vote)
            else:
                self.proposal.result.update_vote(self.vote)
        super(Review, self).save(**kwargs)
    
    def delete(self):
        model = self.__class__
        user_reviews = model._default_manager.filter(
            proposal=self.proposal,
            user=self.user,
        )
        # find previous vote before self
        try:
            previous = user_reviews.filter(submitted_at__lt=self.submitted_at).order_by("-submitted_at")[0]
        except IndexError:
            # did not find a previous which means this must be the only one.
            # treat it as a last, but delete the latest vote.
            self.proposal.result.update_vote(self.vote, removal=True)
            lv = LatestVote.objects.filter(proposal=self.proposal, user=self.user)
            lv.delete()
        else:
            # handle that we've found a previous vote
            # check if self is the last vote
            if self == user_reviews.order_by("-submitted_at")[0]:
                # self is the latest which means we need to treat as last.
                # revert the latest vote to previous vote.
                self.proposal.result.update_vote(self.vote, previous=previous.vote, removal=True)
                lv = LatestVote.objects.filter(proposal=self.proposal, user=self.user)
                lv.update(
                    vote=previous.vote,
                    submitted_at=previous.submitted_at,
                )
            else:
                # self is not the latest so we just need to decrement the
                # comment count
                self.proposal.result.comment_count = models.F("comment_count") - 1
                self.proposal.result.save()
        # in all cases we need to delete the review; let's do it!
        super(Review, self).delete()
    
    def css_class(self):
        return {
            self.VOTES.PLUS_ONE: "plus-one",
            self.VOTES.PLUS_ZERO: "plus-zero",
            self.VOTES.MINUS_ZERO: "minus-zero",
            self.VOTES.MINUS_ONE: "minus-one",
        }[self.vote]


class LatestVote(models.Model):
    VOTES = VOTES
    
    proposal = models.ForeignKey("proposals.Proposal", related_name="votes")
    user = models.ForeignKey(User)
    
    # No way to encode "-0" vs. "+0" into an IntegerField, and I don't feel
    # like some complicated encoding system.
    vote = models.CharField(max_length=2, choices=VOTES.CHOICES)
    submitted_at = models.DateTimeField(default=datetime.now, editable=False)
    
    class Meta:
        unique_together = [("proposal", "user")]
    
    def css_class(self):
        return {
            self.VOTES.PLUS_ONE: "plus-one",
            self.VOTES.PLUS_ZERO: "plus-zero",
            self.VOTES.MINUS_ZERO: "minus-zero",
            self.VOTES.MINUS_ONE: "minus-one",
        }[self.vote]


class ProposalResult(models.Model):
    proposal = models.OneToOneField("proposals.Proposal", related_name="result")
    score = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal("0.00"))
    comment_count = models.PositiveIntegerField(default=1)
    vote_count = models.PositiveIntegerField(default=1)
    plus_one = models.PositiveIntegerField(default=0)
    plus_zero = models.PositiveIntegerField(default=0)
    minus_zero = models.PositiveIntegerField(default=0)
    minus_one = models.PositiveIntegerField(default=0)
    accepted = models.NullBooleanField(choices=[
        (True, "accepted"),
        (False, "rejected"),
        (None, "undecided"),
    ], default=None)
    
    @classmethod
    def full_calculate(cls):
        for proposal in Proposal.objects.all():
            result, created = cls._default_manager.get_or_create(proposal=proposal)
            result.comment_count = Review.objects.filter(proposal=proposal).count()
            result.vote_count = LatestVote.objects.filter(proposal=proposal).count()
            result.plus_one = LatestVote.objects.filter(
                proposal = proposal,
                vote = VOTES.PLUS_ONE
            ).count()
            result.plus_zero = LatestVote.objects.filter(
                proposal = proposal,
                vote = VOTES.PLUS_ZERO
            ).count()
            result.minus_zero = LatestVote.objects.filter(
                proposal = proposal,
                vote = VOTES.MINUS_ZERO
            ).count()
            result.minus_one = LatestVote.objects.filter(
                proposal = proposal,
                vote = VOTES.MINUS_ONE
            ).count()
            result.save()
            cls._default_manager.filter(pk=result.pk).update(score=ProposalScoreExpression())
    
    def update_vote(self, vote, previous=None, removal=False):
        mapping = {
            VOTES.PLUS_ONE: "plus_one",
            VOTES.PLUS_ZERO: "plus_zero",
            VOTES.MINUS_ZERO: "minus_zero",
            VOTES.MINUS_ONE: "minus_one",
        }
        if previous:
            if previous == vote:
                return
            if removal:
                setattr(self, mapping[previous], models.F(mapping[previous]) + 1)
            else:
                setattr(self, mapping[previous], models.F(mapping[previous]) - 1)
        else:
            if removal:
                self.vote_count = models.F("vote_count") - 1
            else:
                self.vote_count = models.F("vote_count") + 1
        if removal:
            setattr(self, mapping[vote], models.F(mapping[vote]) - 1)
            self.comment_count = models.F("comment_count") - 1
        else:
            setattr(self, mapping[vote], models.F(mapping[vote]) + 1)
            self.comment_count = models.F("comment_count") + 1
        self.save()
        model = self.__class__
        model._default_manager.filter(pk=self.pk).update(score=ProposalScoreExpression())


class Comment(models.Model):
    proposal = models.ForeignKey("proposals.Proposal", related_name="comments")
    commenter = models.ForeignKey(User)
    text = MarkupField()
    
    # Or perhaps more accurately, can the user see this comment.
    public = models.BooleanField(choices=[
        (True, "public"),

pycon_project/symposion/review/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from symposion.review.models import Review, Comment, ProposalMessage, VOTES


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["vote", "comment"]
        widgets = { "comment": MarkItUpWidget() }
    
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields["vote"] = forms.ChoiceField(
            widget = forms.RadioSelect(),
            choices = VOTES.CHOICES
        )


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        widgets = { "text": MarkItUpWidget() }


class SpeakerCommentForm(forms.ModelForm):
    class Meta:
        model = ProposalMessage
        fields = ["message"]
        widgets = { "message": MarkItUpWidget() }


class BulkPresentationForm(forms.Form):
    talk_ids = forms.CharField(
        max_length=500,
        help_text="Provide a comma seperated list of talk ids to accept."
    )

pycon_project/templates/review/_review_table.html
{% comment %}
<div>
    <b>View</b>:
        <a href="#type-talk">Talks</a> |
        <a href="#type-panel">Panels</a> |
        <a href="#type-tutorial">Tutorials</a>
        <a href="#type-poster">Posters</a>
</div>

<div class="badges legend">
    <div class="badge extreme">E</div><div class="label"> = EXTREME PyCon</div>
    <div class="clear"></div>
    <div class="badge invited">I</div><div class="label"> = Invited</div>
</div>
{% endcomment %}

{% for type, props in proposals.iteritems %}
    {% for proposal in props %}
        {% if forloop.first %}
            {# <h3 id="type-{{ proposal.get_session_type_display|slugify|lower }}">{{ proposal.get_session_type_display }}{{ props|length|pluralize }}</h3> #}
            <table class="table">
                <thead>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Result
                    </th>
                    <th>
                        Comments
                    </td>
                    <th>
                        +1
                    </th>
                    <th>
                        +0
                    </th>
                    <th>
                        &minus;0
                    </th>
                    <th>
                        &minus;1
                    </th>
                    <th>
                        Total
                    </th>
                </tr>
                </thead>
        <tbody>
        {% endif %}
        <tr class="{{ proposal.latest_vote }}">
            <td>
                <div class="title">
                    <b>#{{ proposal.number }}</b>:
                    <a href="{% url review_detail proposal.pk %}">{{ proposal.title }}</a>
                </div>
                <div class="metadata">
                    {{ proposal.get_audience_level_display }}
                    {{ proposal.get_kind_display }}
                    by
                    {{ proposal.speaker }}
                    {% if proposal.additional_speakers.all %}
                        with
                        {{ proposal.additional_speakers.all|join:", " }}
                    {% endif %}
                    <div class="badges">
                        {% if proposal.extreme_pycon %}
                            <div class="badge extreme">E</div>
                        {% endif %}
                        {% if proposal.invited %}
                            <div class="badge invited">I</div>
                        {% endif %}
                    </div>
                    Allowed to release: {{ proposal.speaker.release_permission }}
                </div>
            </td>
            <td class="result {{ proposal.result.get_accepted_display }}">
                {{ proposal.result.get_accepted_display }}
            </td>
            <td class="count">
                {{ proposal.comment_count }}
            </td>
            <td class="count plus-one">
                {{ proposal.plus_one }}
            </td>
            <td class="count plus-zero">
                {{ proposal.plus_zero }}
            </td>
            <td class="count minus-zero">
                {{ proposal.minus_zero }}
            </td>
            <td class="count minus-one">
                {{ proposal.minus_one }}
            </td>
            <td class="count">
                {{ proposal.total_votes }}
            </td>
        </tr>
        {% if forloop.last %}
            </tbody>
            </table>
        {% endif %}
    {% endfor %}
{% empty %}
    <p>No matching proposals.</p>
{% endfor %}

pycon_project/templates/review/review_detail.html
{% extends "review/base.html" %}
{% load i18n %}
{% load uni_form_tags %}

{% block extra_head %}
    <style>
        .review .uniForm select,
        .review .uniForm textarea
        {
            width: 99%;
        }
        .review-box {
            border-top: 1px solid #CCC;
            margin: 10px 0;
            padding: 10px 10px 0;
        }
        .review-box .vote {
            font-size: 24pt;
            font-weight: bold;
            float: left;
            padding: 10px;
        }
        .review-box .comment {
            margin-left: 80px;
        }
        .review-box .dateline {
            margin-left: 80px;
            font-size: 10pt;
            overflow: auto;
        }
        .review-box .dateline form {
            border: none;
            float: right;
        }
        .vote-count-box .label, .vote-count-box .number {
            float: left;
            margin: 10px;
            overflow: auto;
        }
        .vote-count-box .label {
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            padding: 0px 5px;
        }
        .vote-count-box .number {
            border-right: 1px solid #ccc;
            padding: 0px 10px;
            background: #ccc;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
        }
        .plus-one .vote-count-box.plus-one-box .label,
        .plus-zero .vote-count-box.plus-zero-box .label,
        .minus-zero .vote-count-box.minus-zero-box .label,
        .minus-one .vote-count-box.minus-one-box .label
        {
            background: rgb(72, 120, 88);
            color: #FFF;
        }
        .formHint {
            line-height: 24pt;
        }
        .result {
            font-weight: bold;
            float: right;
            font-size: 24pt;
            border: 10px solid #fff;
            padding: 20px;
            margin: 20px;
            color: white;
            -webkit-border-radius: 5px;
        }
        .result.accepted {
            color: #0C0;
        }
        .result.rejected {
            color: #C00;
        }
        .result.undecided {
            color: #999;
        }
        .result-form input {
            border: none;
            background: #CCC;
        }
        .result-form input:hover {
            border: none;
            background: #000;
            color: #FFF;
        }

        .errorField {
            background: #f2dede;
            padding: 0px 10px;
            margin: 10px 0px;
        }
    </style>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
{% endblock %}

{% block body %}
    <h1>Proposal Review</h1>

    <div class="proposal">
        <div class="result {{ proposal.result.get_accepted_display }}">
            <div class="text">
                {{ proposal.result.get_accepted_display }}
            </div>
            <hr />
            {% if is_reviewer_admin %}
                <form class="result-form" method="POST" action="">
                    {% csrf_token %}
                    {% if proposal.result.get_accepted_display == "accepted" %}
                        <input type="submit" name="result_submit" value="reject" />
                        <input type="submit" name="result_submit" value="undecide" />
                    {% else %}
                        {% if proposal.result.get_accepted_display == "rejected" %}
                            <input type="submit" name="result_submit" value="accept" />
                            <input type="submit" name="result_submit" value="undecide" />
                        {% else %}
                            <input type="submit" name="result_submit" value="accept" />
                            <input type="submit" name="result_submit" value="reject" />
                        {% endif %}
                    {% endif %}
                </form>
            {% endif %}
        </div>
        <h2>#{{ proposal.number }}: {{ proposal.title }}</h2>

        <div class="badges">
            {% if proposal.extreme_pycon %}
                <div class="badge extreme">E</div>
            {% endif %}
            {% if proposal.invited %}
                <div class="badge invited">I</div>
            {% endif %}
        </div>


        <p>
            {% if proposal.cancelled %}
                Cancelled
            {% endif %}
        </p>

        <div>
            {{ proposal.description }}
        </div>

        <p><b>{% trans "Type" %}</b>: {{ proposal.get_kind_display }}</p>
        <p><b>{% trans "Category" %}</b>: {{ proposal.category.name }}</p>

        <h3>{% trans "Abstract" %}</h3>
        <div class="abstract">
            {{ proposal.abstract|safe }}
        </div>

        <p><b>{% trans "Audience level" %}</b>: {{ proposal.get_audience_level_display }}</p>

        <p><b>{% trans "Submitting speaker" %}</b>: {{ proposal.speaker }}</p>
        <p>{{ proposal.speaker.biography_html|safe }}</p>

        {% if proposal.additional_speakers.all %}
            <p><b>{% trans "Additional speakers" %}</b>:</p>
            <ul>
            {% for speaker in proposal.additional_speakers.all %}
                {% if speaker.user %}
                    <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
                {% else %}
                    <li>{{ speaker.email }} &mdash; pending invitation</li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}

        {% if proposal.additional_notes %}
            <h3>{% trans "Additional notes" %} ({% trans "private from submitter"%})</h3>
            <div class="additional_notes">
                {{ proposal.additional_notes|linebreaksbr }}
            </div>
        {% endif %}
    </div>

    {% if is_reviewer_admin or not proposal.invited %}

        <h2>Votes</h2>

        <div class="{{ latest_vote.css_class }}">
            <div class="vote-count-box plus-one-box">
                <div class="label">+1 vote{{ proposal.plus_one|pluralize }}</div>
                <div class="number">{{ proposal.plus_one }}</div>
            </div>
            <div class="vote-count-box plus-zero-box">
                <div class="label">+0 vote{{ proposal.plus_zero|pluralize }}</div>
                <div class="number">{{ proposal.plus_zero }}</div>
            </div>
            <div class="vote-count-box minus-zero-box">
                <div class="label">&minus;0 vote{{ proposal.minus_zero|pluralize }}</div>
                <div class="number">{{ proposal.minus_zero }}</div>
            </div>
            <div class="vote-count-box minus-one-box">
                <div class="label">&minus;1 vote{{ proposal.minus_one|pluralize }}</div>
                <div class="number">{{ proposal.minus_one }}</div>
            </div>
            <div class="vote-count-box total">
                <div class="label">total</div>
                <div class="number">{{ proposal.total_votes }}</div>
            </div>
            <div style="clear: both"></div>
        </div>

        {% for review in reviews %}
            <div class="review-box">
                <div class="vote">{{ review.vote }}</div>
                <div class="comment">{{ review.comment|safe }}</div>
                <div class="dateline">
                    <b>{{ review.user }}</b> {{ review.submitted_at|timesince }} ago
                    {% if is_reviewer_admin %}<form method="POST" action="{% url review_delete review.pk %}">{% csrf_token %}<input type="submit" value="delete" /></form>{% endif %}
                </div>
            </div>
        {% endfor %}

        <hr />

        <h3>Vote and Comment</h3>

        <p>You can revise your vote or comment multiple times with an existing vote.</p>

        <form method="POST" action="" class="uniForm">
            {% csrf_token %}
            <fieldset>
                {{ review_form|as_uni_form }}
                <input class="btn" type="submit" name="vote_submit" value="submit" />
            </fieldset>
        </form>

        <h2>Conversation with Proposer</h2>

        {% for message in proposal.messages.all %}
            <div class="review-box">
                <div class="comment">{{ message.message|safe }}</div>
                <div class="dateline"><b>{{ message.user }}</b> {{ message.submitted_at|timesince }} ago</div>
            </div>
            <div class="clear"></div>
        {% endfor %}

        <h3>Leave a Message</h3>

        <p>You can leave a message for the proposer here.</p>

        <form action="" method="POST" class="uniForm" accept-charset="utf-8">
            {% csrf_token %}
            <fieldset>
                {{ message_form|as_uni_form }}
                <input class="btn" type="submit" name="message_submit" value="submit" />
            </fieldset>
        </form>
    {% endif %}
{% endblock %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $.facebox.settings.loadingImage = '{{ STATIC_URL }}img/facebox/loading.gif';
            $.facebox.settings.closeImage = '{{ STATIC_URL }}img/facebox/closelabel.gif';
            $('#preview').click(function() {
                var raw = $("#id_comment").val();
                $.facebox.loading();
                $.post(
                    '{% url creole_preview %}',
                    {raw: raw},
                    function(data) {
                        $.facebox(data)
                    }
                );
                return false;
            });
        });
    </script>
{% endblock %}