pycon_project/biblion/urls.py
from django.conf.urls.defaults import *

from django.views.generic.simple import direct_to_template


urlpatterns = patterns("",
    url(r'^$', "biblion.views.blog_index", name="blog"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', "biblion.views.blog_post_detail", name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', "biblion.views.blog_post_detail", name="blog_post_pk"),
    url(r'^(?P<section>[-\w]+)/$', "biblion.views.blog_section_list", name="blog_section"),
)

pycon_project/pycon_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
admin.autodiscover()

# from pinax.apps.account.openid_consumer import PinaxConsumer

urlpatterns = patterns("",
    (r'^i18n/', include('django.conf.urls.i18n')),
)

handler500 = "pinax.views.server_error"

urlpatterns += i18n_patterns("",
        url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
        url(r"^program/$", direct_to_template, {"template": "pycon/program.html"}, name="program"),
        url(r"^tutorial/$", direct_to_template, {"template": "pycon/tutorial.html"}, name="tutorial"),
        url(r"^account/signup/$", "pinax.apps.account.views.signup", name="acct_signup"),
        url(r"^account/", include("pinax.apps.account.urls")),
        # url(r"^openid/", include(PinaxConsumer().urls)),
        # url(r"^oauth_access/finish_signup/(?P<service>\w+)/$", "oauth_callbacks.finish_signup", name="oauth_access_finish_signup"),
        # url(r"^oauth_access/", include("oauth_access.urls")),
        url(r"^blog/", include("biblion.urls")),
        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposal/", include("symposion.proposals.urls")),
        url(r"^review/", include("symposion.review.urls")),
        url(r"^waitinglist/", include("pinax.apps.waitinglist.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^mailout/", include("mailout.urls")),
        url(r"^sponsors/", include("symposion.sponsors_pro.urls")),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^creole_preview/$", "pycon_project.views.creole_preview", name="creole_preview"),
        url(r"^feed/(?P<section>\w+)/$", "biblion.views.blog_feed", name="blog_feed"),
        url(r"^markitup/", include("markitup.urls")),
        # url(r"^export_data/speakers\.txt$", "schedule.views.schedule_export_speaker_data"),
        # url(r"^export_data/sponsors\.txt$", "sponsors.views.sponsor_export_data"),
        # url(r"^export_data/panels\.txt$", "schedule.views.schedule_export_panels"),
        url(r"^about/$", direct_to_template, {"template": "pycon/about.html"}, name="about"),
        url(r"^registration/$", direct_to_template, {"template": "pycon/registration.html"}, name="registration"),
        url(r"^venue/$", direct_to_template, {"template": "venue/detail.html"}, name="venue_detail"),
        url(r"^venue/traveling/", direct_to_template, {"template": "venue/traveling.html"}, name="traveling"),
        url(r"^venue/directions/", direct_to_template, {"template": "venue/directions.html"}, name="directions"),
        url(r"^venue/getting-around/", direct_to_template, {"template": "venue/getting_around.html"}, name="getting_around"),
        url(r"^venue/weather/", direct_to_template, {"template": "venue/weather.html"}, name="weather"),
        url(r"^venue/explore/", direct_to_template, {"template": "venue/explore.html"}, name="explore"),
        url(r"^venue/restaurants/", direct_to_template, {"template": "venue/restaurants.html"}, name="restaurants"),
        url(r"^venue/bars/", direct_to_template, {"template": "venue/bars.html"}, name="bars"),
        url(r"^venue/shopping/", direct_to_template, {"template": "venue/shopping.html"}, name="shopping"),
        url(r"^venue/share-room/", direct_to_template, {"template": "venue/share_room.html"}, name="share_room"),


        url(r"^boxes/", include("boxes.urls")),
        # url(r"^", include("wakawaka.urls")),

    )

# urlpatterns += i18n_patterns("",
#     url(r"^$", include(content_patterns)),
#     url(r"^%s/" % settings.PYCON_YEAR, include(content_patterns)),
# )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"^favicon.ico$", redirect_to, {
            "url": settings.STATIC_URL + "img/favicon.ico",
        }),
        url(r"^%s/site_media/media/(?P<path>.*)$" % settings.PYCON_YEAR, "django.views.static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
    )

pycon_project/symposion/proposals/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns("symposion.proposals.views",
    url(r"^submit/$", "proposal_submit", name="proposal_submit"),
    url(r"^(\d+)/$", "proposal_detail", name="proposal_detail"),
    url(r"^(\d+)/edit/$", "proposal_edit", name="proposal_edit"),
    url(r"^(\d+)/file/$", "proposal_file", name="proposal_file"),
    url(r"^(\d+)/speakers/$", "proposal_speaker_manage", name="proposal_speaker_manage"),
    url(r"^(\d+)/cancel/$", "proposal_cancel", name="proposal_cancel"),
    url(r"^(\d+)/leave/$", "proposal_leave", name="proposal_leave"),
)

pycon_project/symposion/proposals/models.py
import datetime

from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe
from django.db import models

from markitup.fields import MarkupField

from symposion.conference.models import PresentationKind, PresentationCategory


class Proposal(models.Model):

    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, _("Novice")),
        (AUDIENCE_LEVEL_INTERMEDIATE, _("Intermediate")),
        (AUDIENCE_LEVEL_EXPERIENCED, _("Experienced")),
    ]

    DURATION_CHOICES = [
        (0, _("No preference")),
        (1, _("I prefer a 30 minute slot")),
        (2, _("I prefer a 45 minute slot")),
    ]

    LANGUAGE_CHOICES = (
        (1, "English"),
        (2, _("Chinese")),
    )

    TYPE_CHOICES = (
        (1, _("Regular Talk (30 minutes)")),
        (2, _("Lightening Talk (5 minutes)")),
    )

    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(
        _("Description"),
        max_length = 400, # @@@ need to enforce 400 in UI
        help_text = _("If your talk is accepted this will be made public and printed in the program. Should be one paragraph, maximum 400 characters.")
    )
    # kind = models.ForeignKey(PresentationKind, verbose_name=_("Kind"))
    kind = models.PositiveSmallIntegerField(_('Type'), choices=TYPE_CHOICES)
    category = models.ForeignKey(PresentationCategory, verbose_name=_("Category"))
    language = models.PositiveSmallIntegerField(_('Default spoken language'), choices=LANGUAGE_CHOICES)
    abstract = MarkupField(
        _("Abstract"),
        help_text = _("Detailed description and outline. Will be made public if your talk is accepted. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>.")
    )
    audience_level = models.IntegerField(_("Audience level"), choices=AUDIENCE_LEVELS)
    additional_notes = MarkupField(
        _("Additional notes"),
        blank=True,
        help_text = _("Anything else you'd like the program committee to know when making their selection: your past speaking experience, open source community experience, etc. Edit using <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/' target='_blank'>Markdown</a>.")
    )
    extreme = models.BooleanField(
        _("Extreme"),
        default=False,
        help_text = _("'Extreme' talks are advanced talks with little or no introductory material. See <a href='http://us.pycon.org/2013/speaker/extreme/' target='_blank'>http://us.pycon.org/2013/speaker/extreme/</a> for details.")
    )
    duration = models.IntegerField(_("Duration"), choices=DURATION_CHOICES, default=0)
    submitted = models.DateTimeField(
        default = datetime.datetime.now,
        editable = False,
    )
    speaker = models.ForeignKey("speakers.Speaker", related_name="proposals")
    additional_speakers = models.ManyToManyField("speakers.Speaker", blank=True)
    cancelled = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

    def can_edit(self):
        return True

    @property
    def speaker_email(self):
        return self.speaker.email

    @property
    def number(self):
        return str(self.pk).zfill(3)

    def speakers(self):
        yield self.speaker
        for speaker in self.additional_speakers.all():
            yield speaker

class ProposalFile(models.Model):
    proposal = models.ForeignKey(Proposal, related_name='files')
    file = models.FileField(upload_to='proposal_files')

pycon_project/symposion/proposals/forms.py
from django import forms
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from markitup.widgets import MarkItUpWidget

from symposion.conference.models import PresentationKind, PresentationCategory
from symposion.proposals.models import Proposal, ProposalFile


class ProposalForm(forms.ModelForm):

    kind = forms.ChoiceField(
        label=_('Types'),
        widget=forms.RadioSelect(),
        choices=Proposal.TYPE_CHOICES,
        required=True,
        help_text=_("If you're not sure which type to choose, select 'Regular Talk' here, and discuss with Program Team for a better arrangement.")
    )

    class Meta:
        model = Proposal
        fields = [
            "title",
            "kind",
            "category",
            "language",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
        ]
        widgets = {
            "description": forms.Textarea(attrs={'class': 'input-xxlarge'}),
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)
        self.fields["category"] = forms.ModelChoiceField(
            label = _('Category'),
            queryset = PresentationCategory.objects.order_by("name")
        )

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class ProposalSubmitForm(ProposalForm):

    def __init__(self, *args, **kwargs):
        super(ProposalSubmitForm, self).__init__(*args, **kwargs)


class ProposalEditForm(ProposalForm):

    class Meta:
        model = Proposal
        fields = [
            "title",
            "kind",
            "category",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
        ]
        widgets = {
            "description": forms.Textarea(attrs={'class': 'input-xxlarge'}),
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class AddSpeakerForm(forms.Form):

    email = forms.EmailField(
        label = "Email address of new speaker (use their email address, not yours)"
    )

    def __init__(self, *args, **kwargs):
        self.proposal = kwargs.pop("proposal")
        super(AddSpeakerForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        value = self.cleaned_data["email"]
        exists = self.proposal.additional_speakers.filter(
            Q(user=None, invite_email=value) |
            Q(user__email=value)
        ).exists()
        if exists:
            raise forms.ValidationError(
                "This email address has already been added to your talk proposal"
            )
        return value

class ProposalFileForm(forms.ModelForm):
    class Meta:
        model = ProposalFile
        exclude = ('proposal',)

pycon_project/templates/proposals/base.html
{% extends "site_base.html" %}

{% block body_class %}full speaker{% endblock %}

{% block body %}
<div class="row">
	<div class="span12">
        {# <h1 class="section-title">{% block subpage_title %}PyCon 2013 <span>Proposals</span>{% endblock %}</h1> #}
        {% block content %}{% endblock %}
    </div>
	<div class="span0">
    </div>
</div>
{% endblock body %}

pycon_project/templates/proposals/proposal_cancel.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>Cancel: {{ proposal.title }}</h1>
    
    <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
        {% csrf_token %}
        <p>Are you sure you want to cancel <b>{{ proposal.title }}</b>?</p>
        <input type="submit" value="I am sure" />
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_detail.html
{% extends "proposals/base.html" %}
{% load i18n %}
{% load uni_form_tags %}

{% block content %}
    <h1>{{ proposal.title }}</h1>

    <p>
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user %}
                <a href="{% url proposal_edit proposal.pk %}">{% trans "Edit" %}</a>
                | <a href="{% url proposal_cancel proposal.pk %}">{% trans "Cancel" %}</a>
            {% else %}
                <a href="{% url proposal_leave proposal.pk %}">{% trans "Leave" %}</a>
            {% endif %}
        {% else %}
            Cancelled
        {% endif %}
    </p>

    <div>
        {{ proposal.description }}
    </div>

    <p><b>{% trans "Type" %}</b>: {{ proposal.get_kind_display }}</p>
    <p><b>{% trans "Category" %}</b>: {{ proposal.category.name }}</p>

    <div>
        {{ proposal.abstract|safe }}
    </div>

    <p><b>{% trans "Audience level" %}</b>: {{ proposal.get_audience_level_display }}</p>

    <p><b>{% trans "Submitting speaker" %}</b>: {{ proposal.speaker }}</p>

    {% if proposal.additional_speakers.all %}
        <p><b>{% trans "Additional speakers" %}</b>:</p>
        <ul>
        {% for speaker in proposal.additional_speakers.all %}
            {% if speaker.user %}
                <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
            {% else %}
                <li>{{ speaker.email }} &mdash; pending invitation</li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endif %}

    {% if request.user == proposal.speaker.user %}
        <p><b>{% trans "Additional notes" %}:</b></p>

        <p>{{ proposal.additional_notes }}</p>
    {% endif %}

    {% comment %}
    <h2>Conversation with Reviewers</h2>

    {% for message in proposal.messages.all %}
        <div class="review-box">
            <div class="comment">{{ message.message|safe }}</div>
            <div class="dateline"><b>{{ message.user }}</b> {{ message.submitted_at|timesince }} ago</div>
        </div>
        <div class="clear"></div>
    {% endfor %}

    <h3>Leave a Message</h3>

    <p>You can leave a message for the proposer here.</p>

    <form action="" method="POST" class="uniForm" accept-charset="utf-8">
        {% csrf_token %}
        <fieldset>
            {{ message_form|as_uni_form }}
            <div class="form_block">
                <input type="submit" name="message_submit" value="submit" />
            </div>
        </fieldset>
    </form>
    {% endcomment %}
{% endblock %}

pycon_project/templates/proposals/proposal_edit.html
{% extends "proposals/base.html" %}

{% load markitup_tags i18n %}
{% load bootstrap %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
    <style>
        .uniForm .formHint {
            width: 99%;
            line-height: 12pt;
            margin-top: 8px;
        }
        #div_id_extreme label {
            display: inline;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Edit: {{ proposal.title }}</h1>
    
    <p><a href="{% url proposal_speaker_manage proposal.pk %}">{% trans "Manage speakers" %}</a></p>
    
    {% markitup_media %}
    <form method="POST" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap }}
            <div class="form-actions">
                <input class="btn btn-primary" type="submit" value="save" />
            </div>
        </fieldset>
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_error.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>{{ body }}</p>
{% endblock %}

pycon_project/templates/proposals/proposal_file.html
{% extends "proposals/base.html" %}

{% load i18n bootstrap %}

{% block content %}
    <h1>{{ proposal.title }} {% trans "Slides/Paper upload" %}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.file }}
        {{ form.file.errors }}
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="{% trans "upload" %}" />
        </div>
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_leave.html
{% extends "proposals/base.html" %}

{% load uni_form_tags %}

{% block content %}
    <h1>Leave: {{ proposal.title }}</h1>
    
    <form method="POST" action="" enctype="multipart/form-data" class="uniForm">
        {% csrf_token %}
        <p>Are you sure you want to no longer speak on <b>{{ proposal.title }}</b>?</p>
        <input type="submit" value="I am sure" />
    </form>
{% endblock %}

pycon_project/templates/proposals/proposal_speaker_manage.html
{% extends "proposals/base.html" %}

{% load i18n bootstrap %}

{% block content %}
    <h1>Proposal: {{ proposal.title }}</h1>
    
    <p><a href="{% url proposal_edit proposal.pk %}">{% trans "Edit proposal" %}</a></p>
    
    <h2>Current Speakers</h2>
    
    {% for speaker in speakers %}
        {% if speaker.user %}
            <p><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</p>
        {% else %}
            <p>{{ speaker.email }} &mdash; pending invitation</p>
        {% endif %}
    {% endfor %}
    
    <h2>Add another speaker</h2>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            {{ add_speaker_form|bootstrap }}
            <div class="form-actions">
                <input class="btn btn-primary" type="submit" value="{% trans "Add speaker" %}" />
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block extra_body %}
    <script type="text/javascript">
    $(function() {
        $("#id_email").focus();
    });
    </script>
{% endblock %}

pycon_project/templates/proposals/proposal_submit.html
{% extends "proposals/base.html" %}

{% load boxes_tags %}
{% load i18n %}
{% load markitup_tags %}
{% load bootstrap %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
{% endblock %}


{% block content %}
    <h1>{% trans "Submit A Proposal" %}</h1>
    
    {% box "example_proposal" %}
    
    {% markitup_media %}
    <form method="post" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap }}
            <div class="form-actions">
                <p>
                    {% trans "You will be able to edit your proposal after it has been submitted. The program committee may ask questions, provide feedback, and even suggest changes to your proposal as part of the review processes." %}
                </p>
                <input class="btn btn-primary" type="submit" name="finish" value="{% trans "Save" %}" />
                <input class="btn" type="submit" name="add-speakers" value="{% trans "Save and Add Additional Speakers" %}" />
            </div>
        </fieldset>
    </form>
{% endblock %}