pycon_project/biblion/urls.py
from django.conf.urls.defaults import *

from django.views.generic.simple import direct_to_template


urlpatterns = patterns("",
    url(r'^$', "biblion.views.blog_index", name="blog"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', "biblion.views.blog_post_detail", name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', "biblion.views.blog_post_detail", name="blog_post_pk"),
    url(r'^(?P<section>[-\w]+)/$', "biblion.views.blog_section_list", name="blog_section"),
)

pycon_project/pycon_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
admin.autodiscover()

# from pinax.apps.account.openid_consumer import PinaxConsumer

urlpatterns = patterns("",
    (r'^i18n/', include('django.conf.urls.i18n')),
)

handler500 = "pinax.views.server_error"

urlpatterns += i18n_patterns("",
        url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
        url(r"^program/$", direct_to_template, {"template": "pycon/program.html"}, name="program"),
        url(r"^tutorial/$", direct_to_template, {"template": "pycon/tutorial.html"}, name="tutorial"),
        url(r"^account/signup/$", "pinax.apps.account.views.signup", name="acct_signup"),
        url(r"^account/", include("pinax.apps.account.urls")),
        # url(r"^openid/", include(PinaxConsumer().urls)),
        # url(r"^oauth_access/finish_signup/(?P<service>\w+)/$", "oauth_callbacks.finish_signup", name="oauth_access_finish_signup"),
        # url(r"^oauth_access/", include("oauth_access.urls")),
        url(r"^blog/", include("biblion.urls")),
        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposal/", include("symposion.proposals.urls")),
        url(r"^review/", include("symposion.review.urls")),
        url(r"^waitinglist/", include("pinax.apps.waitinglist.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^mailout/", include("mailout.urls")),
        url(r"^sponsors/", include("symposion.sponsors_pro.urls")),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^creole_preview/$", "pycon_project.views.creole_preview", name="creole_preview"),
        url(r"^feed/(?P<section>\w+)/$", "biblion.views.blog_feed", name="blog_feed"),
        url(r"^markitup/", include("markitup.urls")),
        # url(r"^export_data/speakers\.txt$", "schedule.views.schedule_export_speaker_data"),
        # url(r"^export_data/sponsors\.txt$", "sponsors.views.sponsor_export_data"),
        # url(r"^export_data/panels\.txt$", "schedule.views.schedule_export_panels"),
        url(r"^about/$", direct_to_template, {"template": "pycon/about.html"}, name="about"),
        url(r"^registration/$", direct_to_template, {"template": "pycon/registration.html"}, name="registration"),
        url(r"^venue/$", direct_to_template, {"template": "venue/detail.html"}, name="venue_detail"),
        url(r"^venue/traveling/", direct_to_template, {"template": "venue/traveling.html"}, name="traveling"),
        url(r"^venue/directions/", direct_to_template, {"template": "venue/directions.html"}, name="directions"),
        url(r"^venue/getting-around/", direct_to_template, {"template": "venue/getting_around.html"}, name="getting_around"),
        url(r"^venue/weather/", direct_to_template, {"template": "venue/weather.html"}, name="weather"),
        url(r"^venue/explore/", direct_to_template, {"template": "venue/explore.html"}, name="explore"),
        url(r"^venue/restaurants/", direct_to_template, {"template": "venue/restaurants.html"}, name="restaurants"),
        url(r"^venue/bars/", direct_to_template, {"template": "venue/bars.html"}, name="bars"),
        url(r"^venue/shopping/", direct_to_template, {"template": "venue/shopping.html"}, name="shopping"),
        url(r"^venue/share-room/", direct_to_template, {"template": "venue/share_room.html"}, name="share_room"),


        url(r"^boxes/", include("boxes.urls")),
        # url(r"^", include("wakawaka.urls")),

    )

# urlpatterns += i18n_patterns("",
#     url(r"^$", include(content_patterns)),
#     url(r"^%s/" % settings.PYCON_YEAR, include(content_patterns)),
# )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"^favicon.ico$", redirect_to, {
            "url": settings.STATIC_URL + "img/favicon.ico",
        }),
        url(r"^%s/site_media/media/(?P<path>.*)$" % settings.PYCON_YEAR, "django.views.static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
    )

pycon_project/symposion/schedule/urls.py
from django.conf.urls.defaults import patterns, url, include
from django.views.generic.simple import direct_to_template


urlpatterns = patterns("symposion.schedule.views",
    #url(r"^$", "schedule_list", name="schedule_list"),
    #url(r"^presentations/(\d+)/", "schedule_presentation", name="schedule_presentation"),
    url(r"^index/$", direct_to_template, {"template": "schedule/index.html"}, name="schedule_index"),
    url(r"^list/(?P<kind_slug>[-\w]+)/", "schedule_presentation_list", name="schedule_presentation_list"),
    url(r"^tutorials/", "schedule_tutorials", name="schedule_tutorials"),
    url(r"^conference/edit/$", "schedule_conference_edit", name="schedule_conference_edit"),
    url(r"^$", "schedule_conference", name="schedule_conference"),
    url(r"^presentations/(\d+)/", "schedule_presentation", name="schedule_presentation"),
    url(r"slot/(\d+)/edit/$", "schedule_slot_edit", name="schedule_slot_edit"),
    url(r"slot/(\d+)/remove/$", "schedule_slot_remove", name="schedule_slot_remove"),
    url(r"^slot/(\d+)/(\w+)/$", "schedule_slot_add", name="schedule_slot_add"),
    url(r"^user_slot/(\d+)/$", "schedule_user_slot_manage", name="schedule_user_slot_manage"),
    url(r"^tracks/$", "track_list", name="schedule_track_list"),
    url(r"^sessions/$", "session_list", name="schedule_session_list"),
    url(r"^track/(\d+)/$", "track_detail", name="schedule_track_detail"),
    url(r"^track/none/$", "track_detail_none", name="schedule_notrack_detail"),
    url(r"^session/(\d+)/$", "session_detail", name="schedule_session_detail"),
    #url(r"^tutorial/(\d+)/$", "tutorial_detail", name="schedule_tutorial_detail"),
    url(r"^bookmarks/(\d+)/(\w+)/$", "schedule_user_bookmarks", name="schedule_user_bookmarks"),
    url(r"^json/$", "schedule_json", name="schedule_json"),
)

pycon_project/symposion/conference/models.py
import datetime

from django.db import models
from django.db.models import Q


class PresentationCategory(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField()
    
    def __unicode__(self):
        return self.name


class PresentationKind(models.Model):
    
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)
    closed = models.NullBooleanField()
    published = models.NullBooleanField()
    
    @classmethod
    def available(cls):
        now = datetime.datetime.now()
        return cls._default_manager.filter(
            Q(start__lt=now) | Q(start=None),
            Q(end__gt=now) | Q(end=None),
            Q(closed=False) | Q(closed=None),
        )
    
    def __unicode__(self):
        return self.name

pycon_project/symposion/schedule/models.py
# encoding: utf-8
import datetime

from django.db import models

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType

from markitup.fields import MarkupField

from symposion.conference.models import PresentationKind, PresentationCategory


class Track(models.Model):
    
    name = models.CharField(max_length=65)
    
    def __unicode__(self):
        return self.name


class Session(models.Model):
    
    track = models.ForeignKey(Track, null=True, related_name="sessions")
    
    def sorted_slots(self):
        ct = ContentType.objects.get_for_model(Presentation)
        return self.slots.filter(kind=ct).order_by("start")
    
    # @@@ cache?
    def start(self):
        slots = self.sorted_slots()
        if slots:
            return list(slots)[0].start
        else:
            return None
    
    # @@@ cache?
    def end(self):
        slots = self.sorted_slots()
        if slots:
            return list(slots)[-1].end
        else:
            return None
    
    def __unicode__(self):
        start = self.start()
        end = self.end()
        if start and end:
            return u"%s: %s — %s" % (
                start.strftime("%a"),
                start.strftime("%X"),
                end.strftime("%X")
            )
        return u""


class SessionRole(models.Model):
    
    SESSION_ROLE_CHAIR = 1
    SESSION_ROLE_RUNNER = 2
    
    SESSION_ROLE_TYPES = [
        (SESSION_ROLE_CHAIR, "Session Chair"),
        (SESSION_ROLE_RUNNER, "Session Runner"),
    ]
    
    session = models.ForeignKey(Session)
    user = models.ForeignKey(User)
    role = models.IntegerField(choices=SESSION_ROLE_TYPES)
    status = models.NullBooleanField()
    
    submitted = models.DateTimeField(default = datetime.datetime.now)
    
    class Meta:
        unique_together = [("session", "user", "role")]


# @@@ precreate the Slots with proposal == None and then making the schedule is just updating slot.proposal and/or title/notes
class Slot(models.Model):
    
    title = models.CharField(max_length=100, null=True, blank=True)
    start = models.DateTimeField()
    end = models.DateTimeField()
    kind = models.ForeignKey(ContentType, null=True, blank=True)
    track = models.ForeignKey(Track, null=True, blank=True, related_name="slots")
    session = models.ForeignKey(Session, null=True, blank=True, related_name="slots")
    
    def content(self):
        if self.kind_id:
            return self.kind.get_object_for_this_type(slot=self)
        else:
            return None
    
    def assign(self, content, old_content=None):
        if old_content is not None:
            old_content.slot = None
            old_content.save()
        content.slot = self
        content.save()
        self.kind = ContentType.objects.get_for_model(content)
        self.save()
    
    def unassign(self):
        content = self.content()
        content.slot = None
        content.save()
        self.kind = None
        self.save()
    
    def __unicode__(self):
        return u"%s (%s: %s — %s)" % (self.title, self.start.strftime("%a"), self.start.strftime("%X"), self.end.strftime("%X"))


class Presentation(models.Model):
    
    PRESENTATION_TYPE_TALK = 1
    PRESENTATION_TYPE_PANEL = 2
    PRESENTATION_TYPE_TUTORIAL = 3
    PRESENTATION_TYPE_POSTER = 4
    
    PRESENTATION_TYPES = [
        (PRESENTATION_TYPE_TALK, "Talk"),
        (PRESENTATION_TYPE_PANEL, "Panel"),
        (PRESENTATION_TYPE_TUTORIAL, "Tutorial"),
        (PRESENTATION_TYPE_POSTER, "Poster")
    ]
    
    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3
    
    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate"),
        (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
    ]

    DURATION_CHOICES = [
        (0, "No preference"),
        (1, "I prefer a 30 minute slot"),
        (2, "I prefer a 45 minute slot"),
    ]
    
    slot = models.OneToOneField(Slot, null=True, blank=True, related_name="presentation")
    
    title = models.CharField(max_length=100)
    description = models.TextField(
        max_length = 400, # @@@ need to enforce 400 in UI
        help_text = "Brief one paragraph blurb (will be public if accepted). Must be 400 characters or less"
    )
    kind = models.ForeignKey(PresentationKind)
    category = models.ForeignKey(PresentationCategory)
    abstract = MarkupField(
        help_text = "More detailed description (will be public if accepted).",
    )
    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)
    duration = models.IntegerField(choices=DURATION_CHOICES)
    
    submitted = models.DateTimeField(
        default = datetime.datetime.now,
        editable = False,
    )
    speaker = models.ForeignKey("speakers.Speaker", related_name="sessions")
    additional_speakers = models.ManyToManyField("speakers.Speaker", blank=True)
    cancelled = models.BooleanField(default=False)
    
    extreme_pycon = models.BooleanField(u"EXTREME PyCon!", default=False)
    invited = models.BooleanField(default=False)
    
    def speakers(self):
        yield self.speaker
        for speaker in self.additional_speakers.all():
            yield speaker
    
    def __unicode__(self):
        return u"%s" % self.title


class Plenary(models.Model):
    
    slot = models.OneToOneField(Slot, null=True, blank=True, related_name="plenary")
    title = models.CharField(max_length=100)
    speaker = models.ForeignKey("speakers.Speaker", null=True, blank=True, related_name="+")
    additional_speakers = models.ManyToManyField("speakers.Speaker", blank=True)
    description = models.TextField(max_length=400, blank=True)


class Recess(models.Model):
    """
    We call this recess due to Break resulting in using break (lower-case "b")
    which is a Python keyword.
    """
    
    slot = models.OneToOneField(Slot, null=True, blank=True, related_name="recess")
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=400, blank=True)


class UserBookmark(models.Model):
    
    user = models.ForeignKey(User)
    presentation = models.ForeignKey(Presentation)
    
    class Meta:
        unique_together = [("user", "presentation")]

pycon_project/symposion/schedule/forms.py
from django import forms
from django.db.models import Q

from symposion.schedule.models import Plenary, Recess, Presentation


class PlenaryForm(forms.ModelForm):
    class Meta:
        model = Plenary
        exclude = ["slot", "additional_speakers"]


class RecessForm(forms.ModelForm):
    class Meta:
        model = Recess
        exclude = ["slot"]


def presentation_queryset(include=None):
    qs = Presentation.objects.all()

    if include:
        qs = qs.filter(Q(slot=None) | Q(pk=include.pk))
    else:
        qs = qs.filter(slot=None)
    qs = qs.order_by("pk")
    return qs


class PresentationModelChoiceField(forms.ModelChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs["queryset"] = Presentation.objects.none()
        super(PresentationModelChoiceField, self).__init__(*args, **kwargs)

    def label_from_instance(self, obj):
        return u"%d: %s" % (obj.pk, obj.title)


class PresentationForm(forms.Form):

    presentation = PresentationModelChoiceField()

    def __init__(self, *args, **kwargs):
        presentation = kwargs.get("initial", {}).get("presentation", None)
        super(PresentationForm, self).__init__(*args, **kwargs)
        if presentation:
            self.fields["presentation"].queryset = presentation_queryset(include=presentation)
        else:
            self.fields["presentation"].queryset = presentation_queryset()

    def save(self, commit=True):
        return self.cleaned_data["presentation"]

pycon_project/templates/schedule/base.html
{% extends "site_base.html" %}

{% block body_class %}full schedule{% endblock %}

{% block subnav %}
    <a href="{% url schedule_tutorials %}">Tutorial Schedule</a>
    |
    <a href="{% url schedule_conference %}">Conference Schedule</a>
    {% comment %}
    |
    <a href="{% url schedule_list_talks %}">List of Accepted Talks and Panels</a>
    |
    <a href="{% url schedule_list_posters %}">List of Accepted Posters</a>
    {% endcomment %}
    |
    <a href="{% url wakawaka_page 'openspaces/index' %}">OpenSpaces</a>
{% endblock %}


{% block right %}{% endblock %}

pycon_project/templates/schedule/list_posters.html
{% extends "schedule/base.html" %}

{% load boxes_tags %}

{% block extra_head %}
    <style>
        .session {
            margin-top: 10px;
        }
        .title {
            font-size: 14pt;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Accepted Posters</h1>
    
    <div>
        {% box "posters-intro" %}
    </div>
    
    {% for poster in posters %}
        <div class="session">
            <div class="title">
                <a href="{% url schedule_presentation poster.pk %}">{{ poster.title }}</a>
            </div>
            <div class="metadata">
                {{ poster.get_audience_level_display }}
                {{ poster.get_session_type_display }}
                by
                {{ poster.speaker }}
                {% if poster.additional_speakers.all %}
                    with
                    {{ poster.additional_speakers.all|join:", " }}
                {% endif %}
            </div>
        </div>
    {% empty %}
        <p>No accepted posters yet.</p>
    {% endfor %}
    
{% endblock %}

pycon_project/templates/schedule/list_talks.html
{% extends "schedule/base.html" %}

{% block extra_head %}
    <style>
        .session {
            margin-top: 10px;
        }
        .title {
            font-size: 14pt;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Accepted Talks and Panels</h1>
    
    <div class="badges legend">
        <div class="badge extreme">E</div><div class="label"> = EXTREME PyCon</div>
        <div class="clear"></div>
        <div class="badge invited">I</div><div class="label"> = Invited</div>
    </div>
    
    {% for talk in talks %}
        <div class="session">
            <div class="title">
                <a href="{% url schedule_presentation talk.pk %}">{{ talk.title }}</a>
            </div>
            <div class="metadata">
                {{ talk.get_audience_level_display }}
                {{ talk.get_session_type_display }}
                by
                {{ talk.speaker }}
                {% if talk.additional_speakers.all %}
                    with
                    {{ talk.additional_speakers.all|join:", " }}
                {% endif %}
                <div class="badges">
                    {% if talk.extreme_pycon %}
                        <div class="badge extreme">E</div>
                    {% endif %}
                    {% if talk.invited %}
                        <div class="badge invited">I</div>
                    {% endif %}
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    {% empty %}
        <p>No accepted talks or panels yet.</p>
    {% endfor %}
    
{% endblock %}

pycon_project/templates/schedule/presentation_detail.html
{% extends "schedule/base.html" %}

{% load timezone_filters %}

{% block extra_head %}
    <style>
        a.unbookmark {
            text-decoration: none;
            padding-left: 20px;
            background: url(/2011/site_media/static/img/star.png) no-repeat left;
        }
        a.bookmark {
            text-decoration: none;
            padding-left: 20px;
            background: url(/2011/site_media/static/img/star_unselected.png) no-repeat left;
        }
        div.slot {
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>{{ presentation.title }}</h1>
    
    {% if user.is_authenticated %}
        {% if presentation.bookmarked %}
            <p><a href="{% url schedule_user_slot_manage presentation.id %}" class="unbookmark">unbookmark</a></p>
        {% else %}
            <p><a href="{% url schedule_user_slot_manage presentation.id %}" class="bookmark">bookmark</a></p>
        {% endif %}
    {% else %}
        <p><a href="{% url acct_login %}?next={{ request.path }}">log in</a> to bookmark this presentaton</p>
    {% endif %}
    
    <div class="badges">
        {% if presentation.extreme_pycon %}
            <div class="badge extreme">E</div>
        {% endif %}
        {% if presentation.invited %}
            <div class="badge invited">I</div>
        {% endif %}
        <div class="clear"></div>
    </div>
    
    <div class="presentation_types">{{ presentation.get_audience_level_display }} / {{ presentation.get_presentation_type_display }}</div>
    
    <div class="speakers">
        {% for speaker in presentation.speakers %}
        <a href="{% url speaker_profile speaker.id %}">{{ speaker }}</a>
        {% if not forloop.last %}, {% endif %}{% endfor %}
    </div>
    
    {% if presentation.slot %}
        <div class="slot">{{ presentation.slot.start|localtime:timezone|date:"F jS" }} {{ presentation.slot.start|localtime:timezone|date:"P" }} &ndash; {{ presentation.slot.end|localtime:timezone|date:"P" }}</div>
    {% endif %}
    
    <div class="description">{{ presentation.description }}</div>
    
    <h3>Abstract</h3>
    
    <div class="abstract">{{ presentation.abstract_html|safe }}</div>
{% endblock %}

{% block extra_body %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("a.bookmark").live("click", function() {
                aElem = $(this);
                $.ajax({
                    type: "POST",
                    url: this.href,
                    data: "action=add;csrfmiddlewaretoken={{ csrf_token }}",
                    success: function() {
                        aElem.text("unbookmark");
                        aElem.removeClass("bookmark");
                        aElem.addClass("unbookmark");
                    },
                    error: function(xhr, options, error) {
                        alert(xhr.status);
                    }
                });
                return false;
            });
            $("a.unbookmark").live("click", function() {
                aElem = $(this);
                $.ajax({
                    type: "POST",
                    url: this.href,
                    data: "action=delete;csrfmiddlewaretoken={{ csrf_token }}",
                    success: function(response) {
                        aElem.text("bookmark");
                        aElem.removeClass("unbookmark");
                        aElem.addClass("bookmark");
                    },
                    error: function(xhr, options, error) {
                        alert(xhr.status);
                    }
                });
                return false;
            });
        });
    </script>
{% endblock %}

pycon_project/templates/schedule/session_list.html
{% extends "schedule/base.html" %}

{% block body %}
    <h1>Sessions</h1>
    
    <ul>
        {% for session in sessions %}
            {% if session.sorted_slots %}
                <li>
                    <a href="{% url schedule_session_detail session.pk %}">[{{ session.track }}] {{ session }}</a>
                    <ul>
                        {% for role in session.sessionrole_set.all %}
                            <li><b>{{ role.get_role_display }}: {{ role.user }}</b></li>
                        {% empty %}
                            <li><b>No volunteers signed up</b></li>
                        {% endfor %}
                        {% for slot in session.sorted_slots %}
                            <li>{{ slot }}: {% if slot.content %}<a href="{% url schedule_presentation slot.content.pk %}">{{ slot.content }}</a>{% endif %}</li>
                        {% empty %}
                            <li>No slots in session.</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endif %}
        {% empty %}
            <li>No sessions defined.</li>
        {% endfor %}
    </ul>
    
{% endblock %}

pycon_project/templates/schedule/tmp_session_detail.html
{% extends "schedule/base.html" %}

{% load uni_form_tags %}

{% block extra_head %}
    <style>
        .review .uniForm select,
        .review .uniForm textarea
        {
            width: 99%;
        }
        .review-box {
            border-top: 1px solid #CCC;
            margin: 10px 0;
            padding: 10px 10px 0;
        }
        .review-box .vote {
            font-size: 24pt;
            font-weight: bold;
            float: left;
            padding: 10px;
        }
        .review-box .comment {
            margin-left: 80px;
        }
        .review-box .dateline {
            margin-left: 80px;
            font-size: 10pt;
        }
        .plus-one .vote-count-box.plus-one-box .label,
        .plus-zero .vote-count-box.plus-zero-box .label,
        .minus-zero .vote-count-box.minus-zero-box .label,
        .minus-one .vote-count-box.minus-one-box .label
        {
            background: rgb(72, 120, 88);
            color: #FFF;
        }
        .formHint {
            line-height: 24pt;
        }
        .result {
            font-weight: bold;
            float: right;
            font-size: 16pt;
        }
        .result.accepted {
            color: #0C0;
        }
        .result.rejected {
            color: #C00;
        }
        .result.undecided {
            color: #999;
        }
        .result-form input {
            border: none;
            background: #CCC;
        }
        .result-form input:hover {
            border: none;
            background: #000;
            color: #FFF;
        }
    </style>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/facebox.css" />
{% endblock %}

{% block subnav %}
    <a href="{% url schedule_list_talks %}">List of Accepted Talks and Panels</a>
    |
    <a href="{% url schedule_tutorials %}">Tutorial Schedule</a>
{% endblock %}

{% block body %}
    <h1>{{ proposal.title }}</h1>

    <div class="proposal">
        <div class="badges">
            {% if proposal.extreme_pycon %}
                <div class="badge extreme">E</div>
            {% endif %}
            {% if proposal.invited %}
                <div class="badge invited">I</div>
            {% endif %}
        </div>

        <div class="clear"></div>

        <div>
            {{ proposal.description }}
        </div>

        <p><b>Type</b>: {{ proposal.get_kind_display }}</p>

        <h3>Abstract</h3>
        <div class="abstract">
            {{ proposal.abstract_html|safe }}
        </div>

        <p><b>Audience level</b>: {{ proposal.get_audience_level_display }}</p>

        <p><b>Speaker</b>: {{ proposal.speaker }}</p>
        <p>{{ proposal.speaker.biography_html|safe }}</p>

        {% if proposal.additional_speakers.all %}
            <p><b>Additional speakers</b>:</p>
            <ul>
            {% for speaker in proposal.additional_speakers.all %}
                {% if speaker.user %}
                    <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}js/facebox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $.facebox.settings.loadingImage = '{{ STATIC_URL }}img/facebox/loading.gif';
            $.facebox.settings.closeImage = '{{ STATIC_URL }}img/facebox/closelabel.gif';
            $('#preview').click(function() {
                var raw = $("#id_comment").val();
                $.facebox.loading();
                $.post(
                    '{% url creole_preview %}',
                    {raw: raw},
                    function(data) {
                        $.facebox(data)
                    }
                );
                return false;
            });
        });
    </script>
{% endblock %}

pycon_project/templates/schedule/track_detail.html
{% extends "schedule/base.html" %}

{% block body %}
    
    <p><a href="{% url schedule_track_list %}">Tracks</a> &raquo;</p>
    
    <h1>Track: {{ track }}</h1>
    
    <h2>Sessions</h2>
    
    <ul>
        {% for session in track.sessions.all %}
            {% if session.sorted_slots %}
                <li>
                    <a href="{% url schedule_session_detail session.pk %}">[{{ session.track }}] {{ session }}</a>
                    <ul>
                        {% for role in session.sessionrole_set.all %}
                            <li><b>{{ role.get_role_display }}: {{ role.user }}</b></li>
                        {% empty %}
                            <li><b>No volunteers signed up</b></li>
                        {% endfor %}
                        {% for slot in session.sorted_slots %}
                            <li>{{ slot }}: {% if slot.content %}<a href="{% url schedule_presentation slot.content.pk %}">{{ slot.content }}</a>{% endif %}</li>
                        {% empty %}
                            <li>No slots in session.</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endif %}
        {% empty %}
            <li>No sessions in track.</li>
        {% endfor %}
    </ul>
    
{% endblock %}